### ISSUE TITLE
Unable to load in Python 3.9

### ISSUE THREAD

**Issue by AngellusMortis** [vaaaaanquish/xontrib-powerline2#17]
As soon as I got Python 3.9, my fork of `xontrib-powerline` started breaking. I found yours and it has the same problem.

I am able to reproduce this on multiple machines running Arch Linux with the latest Xonsh (0.9.24) from official repos:

```
Traceback (most recent call last):
    File "/usr/lib/python3.9/site-packages/xonsh/__amalgam__.py", line 10835, in xontribs_load
        update_context(name, ctx=ctx)
    File "/usr/lib/python3.9/site-packages/xonsh/__amalgam__.py", line 10780, in update_context
        modctx = xontrib_context(name)
    File "/usr/lib/python3.9/site-packages/xonsh/__amalgam__.py", line 10746, in xontrib_context
        m = importlib.import_module(spec.name)
    File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
    File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
    File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
    File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
    File "<frozen importlib._bootstrap_external>", line 786, in exec_module
    File "/usr/lib/python3.9/site-packages/xonsh/__amalgam__.py", line 24307, in get_code
        code = execer.compile(src, glbs=ctx, locs=ctx)
    File "/usr/lib/python3.9/site-packages/xonsh/__amalgam__.py", line 23992, in compile
        tree = self.parse(input, ctx, mode=mode, filename=filename, transform=transform)
    File "/usr/lib/python3.9/site-packages/xonsh/__amalgam__.py", line 23952, in parse
        tree, input = self._parse_ctx_free(input, mode=mode, filename=filename)
    File "/usr/lib/python3.9/site-packages/xonsh/__amalgam__.py", line 24076, in _parse_ctx_free
        tree = self.parser.parse(
    File "/usr/lib/python3.9/site-packages/xonsh/parsers/base.py", line 497, in parse
        tree = self.parser.parse(input=s, lexer=self.lexer, debug=debug_level)
    File "/usr/lib/python3.9/site-packages/xonsh/ply/ply/yacc.py", line 335, in parse
        return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
    File "/usr/lib/python3.9/site-packages/xonsh/ply/ply/yacc.py", line 1122, in parseopt_notrack
        p.callable(pslice)
    File "/usr/lib/python3.9/site-packages/xonsh/parsers/base.py", line 2221, in p_atom_expr
        p[0] = self.apply_trailers(p[1], p[2])
    File "/usr/lib/python3.9/site-packages/xonsh/parsers/base.py", line 2215, in apply_trailers
        assert False
AssertionError
Failed to load xontrib powerline2.
```

**Comment by vaaaaanquish** [comment]
Thanks. We'll see.

**Comment by vaaaaanquish** [comment]
Thanks. I was able to reproduce it.
```
$ docker pull python:3.9
$ docker run -it python bash
// --- in docker ---
$ pip install xonsh
$ pip install xontrib-powerline2
$ touch ~/.xonshrc
$ echo "\$XONSH_SHOW_TRACEBACK = True" > ~/.xonshrc
$ echo "xontrib load powerline2" >> ~/.xonshrc
$ xonsh
```
```
root@eb6dc2da9f7e:/# xonsh
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/xonsh/xontribs.py", line 124, in xontribs_load
    update_context(name, ctx=ctx)
  File "/usr/local/lib/python3.9/site-packages/xonsh/xontribs.py", line 69, in update_context
    modctx = xontrib_context(name)
  File "/usr/local/lib/python3.9/site-packages/xonsh/xontribs.py", line 35, in xontrib_context
    m = importlib.import_module(spec.name)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 786, in exec_module
  File "/usr/local/lib/python3.9/site-packages/xonsh/imphooks.py", line 123, in get_code
    code = execer.compile(src, glbs=ctx, locs=ctx)
  File "/usr/local/lib/python3.9/site-packages/xonsh/execer.py", line 135, in compile
    tree = self.parse(input, ctx, mode=mode, filename=filename, transform=transform)
  File "/usr/local/lib/python3.9/site-packages/xonsh/execer.py", line 95, in parse
    tree, input = self._parse_ctx_free(input, mode=mode, filename=filename)
  File "/usr/local/lib/python3.9/site-packages/xonsh/execer.py", line 219, in _parse_ctx_free
    tree = self.parser.parse(
  File "/usr/local/lib/python3.9/site-packages/xonsh/parsers/base.py", line 497, in parse
    tree = self.parser.parse(input=s, lexer=self.lexer, debug=debug_level)
  File "/usr/local/lib/python3.9/site-packages/xonsh/ply/ply/yacc.py", line 335, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/usr/local/lib/python3.9/site-packages/xonsh/ply/ply/yacc.py", line 1122, in parseopt_notrack
    p.callable(pslice)
  File "/usr/local/lib/python3.9/site-packages/xonsh/parsers/base.py", line 2221, in p_atom_expr
    p[0] = self.apply_trailers(p[1], p[2])
  File "/usr/local/lib/python3.9/site-packages/xonsh/parsers/base.py", line 2215, in apply_trailers
    assert False
AssertionError
Failed to load xontrib powerline2.
```

I'm guessing it's because powerline2 doesn't support the new syntax, I'll check for updates to xonsh.

**Comment by vaaaaanquish** [comment]
An error occurs when attempting to define this function. This may be a problem with Xonsh.
```
$ def alias(f):
       aliases[f.__name__] = f
       return f

xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/xonsh/ptk_shell/shell.py", line 238, in _push
    code = self.execer.compile(src, mode="single", glbs=self.ctx, locs=None)
  File "/usr/local/lib/python3.9/site-packages/xonsh/execer.py", line 135, in compile
    tree = self.parse(input, ctx, mode=mode, filename=filename, transform=transform)
  File "/usr/local/lib/python3.9/site-packages/xonsh/execer.py", line 95, in parse
    tree, input = self._parse_ctx_free(input, mode=mode, filename=filename)
  File "/usr/local/lib/python3.9/site-packages/xonsh/execer.py", line 219, in _parse_ctx_free
    tree = self.parser.parse(
  File "/usr/local/lib/python3.9/site-packages/xonsh/parsers/base.py", line 497, in parse
    tree = self.parser.parse(input=s, lexer=self.lexer, debug=debug_level)
  File "/usr/local/lib/python3.9/site-packages/xonsh/ply/ply/yacc.py", line 335, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/usr/local/lib/python3.9/site-packages/xonsh/ply/ply/yacc.py", line 1122, in parseopt_notrack
    p.callable(pslice)
  File "/usr/local/lib/python3.9/site-packages/xonsh/parsers/base.py", line 2221, in p_atom_expr
    p[0] = self.apply_trailers(p[1], p[2])
  File "/usr/local/lib/python3.9/site-packages/xonsh/parsers/base.py", line 2215, in apply_trailers
    assert False
AssertionError
```

**Comment by vaaaaanquish** [comment]
I found the smallest error and will report it to Xonsh.
```
def test(x):
    return x[x.__name__]
```

powerline2 is supported by the following
```
$ def alias(f):
    module_name = f.__name__
    aliases[module_name] = f
    return f
```

**Comment by vaaaaanquish** [comment]
Same here.
```
@register_sec
def rtns(sample=False):
    if sample:
        return Section(' ! ', *$PL_COLORS['rtns'])
    if __xonsh__.history.rtns and __xonsh__.history.rtns[-1] != 0:
         return Section(' ! ', *$PL_COLORS['rtns'])

xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/xonsh/ptk_shell/shell.py", line 238, in _push
    code = self.execer.compile(src, mode="single", glbs=self.ctx, locs=None)
  File "/usr/local/lib/python3.9/site-packages/xonsh/execer.py", line 135, in compile
    tree = self.parse(input, ctx, mode=mode, filename=filename, transform=transform)
  File "/usr/local/lib/python3.9/site-packages/xonsh/execer.py", line 95, in parse
    tree, input = self._parse_ctx_free(input, mode=mode, filename=filename)
  File "/usr/local/lib/python3.9/site-packages/xonsh/execer.py", line 219, in _parse_ctx_free
    tree = self.parser.parse(
  File "/usr/local/lib/python3.9/site-packages/xonsh/parsers/base.py", line 497, in parse
    tree = self.parser.parse(input=s, lexer=self.lexer, debug=debug_level)
  File "/usr/local/lib/python3.9/site-packages/xonsh/ply/ply/yacc.py", line 335, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/usr/local/lib/python3.9/site-packages/xonsh/ply/ply/yacc.py", line 1122, in parseopt_notrack
    p.callable(pslice)
  File "/usr/local/lib/python3.9/site-packages/xonsh/parsers/base.py", line 2221, in p_atom_expr
    p[0] = self.apply_trailers(p[1], p[2])
  File "/usr/local/lib/python3.9/site-packages/xonsh/parsers/base.py", line 2215, in apply_trailers
    assert False
AssertionError
```

**Comment by vaaaaanquish** [comment]
@AngellusMortis 
Python 3.9 does not seem to be supported yet. We need to commit to xonsh
https://github.com/xonsh/xonsh/pull/3588

**Comment by vaaaaanquish** [comment]
This issue will be closed once. Please commit to xonsh.
